Inicio: home
Sobre: about
Servicos: services
Galeria: gallery
Precos: prices
Contato: contact
TextoSobre: Created in 2015 by Camilla França, the Pixel Cakes join gourmet, art and differentiated flavor in her candies. Our mission is offer to our clients, acessible gourmet candies.
TextoServico: We participate in start-ups markets, art's exhibition, events in general where there are candies, and also, we accept orders.
Confira: check it
TabelaPrecos: prices' table
TextoPrecos: Beyond pretty, Pixel Cakes' candies are cheap. Don't believe? Check it!
SaibaMais: know more