Inicio: inicio
Sobre: sobre
Servicos: serviços
Galeria: galeria
Precos: preços
Contato: contato
TextoSobre: Criada em 2015, por Camilla França, a Pixel Cakes junta gourmet, arte e sabor diferenciado em seus doces. Nossa missão é oferecer aos nossos clientes, doces gourmet acessíveis.
TextoServico: Participamos de feiras de start-ups, exposições de arte, eventos em geral onde cabem docinhos, e também aceitamos encomendas.
Confira: confira
TabelaPrecos: Tabela de preços
TextoPrecos: Além de bonitos, os docinhos da Pixel Cakes são baratos. Não acredita? Confere aí!
SaibaMais: saiba mais
Produtos: produtos